### ISSUE TITLE
White screen on accessing pages other than homepage

### ISSUE THREAD

**Issue by changjy44** [CS3219-AY2324S1/ay2324s1-course-assessment-g43#28]
Steps to recreate the bug
1. Go to localhost:5173/me

White screen appears

**Comment by clevon-w** [comment]
The pages that have the white screen of death:

1. my profile page, localhost:5173/me
a. blank because when the page component tries to get user from local storage and userr is not logged in so its returning undefined.
b. useEffect with [] is calling `populateStateWithUserById()` which then calls `getUserById`
c. intended behaviour should be userId can be undefined, send it to the backend, and backend throw 500
2. browse pages, /browse-user and /browse-admin
a. both are loading but when trying to get questions, auth.js middleware is getting called to authenticate the user.
b. since user is not logged in, auth.js is throwing a 401
3. update user page, seems to have the same behaviour as /me page
4. /update-question got selectedQuestion undefined, should be same behaviour as me page
5. /session too

the plan to solve this. 
create a generic error page that will be shown for different error types. depending on the error code, can show different content. like maybe 401 will say oh u havent log in and show a login button that redirects users, then 500 is just something went wrong with a go to home page button etc
